name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Type check files
        run: yarn tsc
