name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Elasticsearch
        run: docker-compose up -d elasticsearch

      - name: Wait on Elasticsearch
        run: curl curl -X GET "http://localhost:9200/_cluster/health?pretty"

      - name: Seed Elasticsearch
        run: yarn es:seed

      - name: Run tests
        run: yarn jest
